# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import msu_logging_pb2 as msu__logging__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in msu_logging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscribeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTranscribeResult = channel.unary_unary(
                '/msu_logging.Transcribe/SendTranscribeResult',
                request_serializer=msu__logging__pb2.TranscribeResult.SerializeToString,
                response_deserializer=msu__logging__pb2.Result.FromString,
                _registered_method=True)


class TranscribeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTranscribeResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscribeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTranscribeResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTranscribeResult,
                    request_deserializer=msu__logging__pb2.TranscribeResult.FromString,
                    response_serializer=msu__logging__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msu_logging.Transcribe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('msu_logging.Transcribe', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transcribe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTranscribeResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/msu_logging.Transcribe/SendTranscribeResult',
            msu__logging__pb2.TranscribeResult.SerializeToString,
            msu__logging__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProtocolStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendProtocolResult = channel.unary_unary(
                '/msu_logging.Protocol/SendProtocolResult',
                request_serializer=msu__logging__pb2.ProtocolResult.SerializeToString,
                response_deserializer=msu__logging__pb2.Result.FromString,
                _registered_method=True)


class ProtocolServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendProtocolResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProtocolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendProtocolResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SendProtocolResult,
                    request_deserializer=msu__logging__pb2.ProtocolResult.FromString,
                    response_serializer=msu__logging__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msu_logging.Protocol', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('msu_logging.Protocol', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Protocol(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendProtocolResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/msu_logging.Protocol/SendProtocolResult',
            msu__logging__pb2.ProtocolResult.SerializeToString,
            msu__logging__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
