version: "3"

tasks:
  protos:
    cmds:
    - python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. msu_logging.proto
  runprod:
    cmds:
    - python main.py
  rundev:
    cmds:
    - python main.py --backend_url=localhost --rabbitmq_url=localhost